@startuml JewerlyStoreSystem
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml


title Jewerly Store System Component Diagram

Person(Customer, "Customer", "Description of external person.")
Person(Seller, "Seller", "Operates with order, confirms manufacturing for the user")
Person(ApiUser, "API user", "Description of external person.")
Person(Operator, "Operator", "Takes order in work, manufactures jewerly")
Person(Developer, "Developer", "")

Container_Boundary(JewerlyStoreSystem, "Jewerly Store System\n[Software system]") {
    Container(InternetShop, "Internet Shop", "Vue, TypeScript, Threejs", "User can make an order, upload 3d model, work in 3d editor")
    Component(ShopApi, "Shop API", "SpringBoot", "- provide list of shop items\n- receives user generated or uploaded 3d file\n- save information about order from customer perspective")

    Container(CRM, "CRM", "Vue, Typescript", "Description of web browser container role/responsibility.")
    Component(CrmApi, "CRM API", "SpringBoot", "Description of container role/responsibility.")

    Component(MesApi, "MES API", "C#", "- Assigns orders on operators\n- Shows list of orders\n- Calculates price of the order")
    Container(MES, "MES", "React, typescript", "provide interface to assign orders on operators, shows list of orders")
    ContainerQueue(MessagesQueue, "Messages Queue", "RabbitMQ", "Send messages about new orders, changes of statuses between containers, has several topics")
    ComponentDb(MesDB, "MES db", "PostgreSQL", "Holds information about orders, its assignments on operators and statuses from MES perspective")

    Component(Jaeger, "Tracing System", "Jaeger", "")
    Component(JaegerUI, "Tracing System User Interface", "JaegerUI", "")
    ComponentDb(JaegerDB, "Tracing System Data Base", "JaegerDB", "")

    Component(Kibana, "", "Kibana", "")
    Component(KibanaUI, "", "Kibana User Interface", "")

    Component(ElasticSearch, "", "ElasticSearch", "")

    Component(Logstash, "", "Logstash", "")

    Component(3dFilesStorage, "3d files storage", "S3-based storage", "stores 3d files so that can be calculated")

    ComponentDb(ShopDB, "Shop DB", "PostgreSQL", "Holds main information about work with customers and its orders")
}

Rel(Customer, InternetShop, "")
Rel(Seller, CRM, "")
Rel(ApiUser, MesApi, "")
Rel(Operator, MES, "")
Rel(Developer, JaegerUI, "")
Rel(Developer, KibanaUI, "")

Rel(InternetShop, ShopApi, "")

Rel(CRM, CrmApi, "")

Rel(MesApi, 3dFilesStorage, "")
Rel(MesApi, MessagesQueue, "Consuming and check cache before start calculations")
Rel(MesApi, MesDB, "")
Rel(MesApi, Logstash, "")

Rel(MES, MesApi, "")

Rel(ShopApi, ShopDB, "")
Rel(ShopApi, 3dFilesStorage, "uploads files")
Rel(ShopApi, Jaeger, "")
Rel(ShopApi, Logstash, "")

Rel(CrmApi, 3dFilesStorage, "")
Rel(CrmApi, ShopDB, "")
Rel(CrmApi, MessagesQueue, "")
Rel(CrmApi, Jaeger, "")
Rel(CrmApi, Logstash, "")

Rel(MessagesQueue, CrmApi, "")
Rel(MessagesQueue, MesApi, "")

Rel(MesApi, Jaeger, "")
Rel(MesApi, Logstash, "")

Rel(JaegerUI, Jaeger, "")
Rel(Jaeger, JaegerDB, "")

Rel(Kibana, KibanaUI, "")

Rel(Kibana, ElasticSearch, "")

Rel(Logstash, ElasticSearch, "")

@enduml
